### ISSUE TITLE
IndexOutOfBounds when adding player

### ISSUE THREAD

**Issue by Kauko** [aoh/luola#8]
```
java.lang.IndexOutOfBoundsException
	at clojure.lang.PersistentVector.arrayFor(PersistentVector.java:158)
	at clojure.lang.PersistentVector.nth(PersistentVector.java:162)
	at clojure.lang.RT.nth(RT.java:853)
	at clojure.core$rand_nth.invokeStatic(core.clj:6952)
	at clojure.core$rand_nth.invoke(core.clj:6945)
	at luola.main$empty_spawn_cell.invokeStatic(main.clj:131)
	at luola.main$empty_spawn_cell.invoke(main.clj:130)
	at luola.main$maybe_add_player_BANG_$fn__12912.invoke(main.clj:425)
	at luola.main$maybe_add_thing_BANG_$fn__12907.invoke(main.clj:413)
	at luola.main$alter_world_BANG_$fn__12779.invoke(main.clj:34)
	at clojure.lang.Atom.swap(Atom.java:37)
	at clojure.core$swap_BANG_.invokeStatic(core.clj:2260)
	at clojure.core$swap_BANG_.invoke(core.clj:2253)
	at luola.main$alter_world_BANG_.invokeStatic(main.clj:32)
	at luola.main$alter_world_BANG_.invoke(main.clj:31)
	at luola.main$maybe_add_thing_BANG_.invokeStatic(main.clj:409)
	at luola.main$maybe_add_thing_BANG_.invoke(main.clj:405)
	at luola.main$maybe_add_player_BANG_.invokeStatic(main.clj:423)
	at luola.main$maybe_add_player_BANG_.invoke(main.clj:422)
	at luola.main$fn__12990.invokeStatic(main.clj:591)
	at luola.main$fn__12990.invoke(main.clj:588)
	at compojure.core$make_route$fn__1914.invoke(core.clj:135)
	at compojure.core$wrap_route_middleware$fn__1907.invoke(core.clj:122)
	at compojure.core$wrap_route_info$fn__1911.invoke(core.clj:126)
	at compojure.core$if_route$fn__1865.invoke(core.clj:45)
	at compojure.core$if_method$fn__1855.invoke(core.clj:27)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.core$routing$fn__1921.invoke(core.clj:151)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.core$routing.invokeStatic(core.clj:151)
	at compojure.core$routing.doInvoke(core.clj:148)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at compojure.core$routes$fn__1925.invoke(core.clj:156)
	at compojure.core$if_context$fn__1983.invoke(core.clj:220)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__10504.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__4759.invoke(core.clj:2515)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at ring.swagger.middleware$wrap_swagger_data$fn__7626.invoke(middleware.clj:33)
	at ring.middleware.http_response$wrap_http_response$fn__2524.invoke(http_response.clj:8)
	at ring.swagger.middleware$wrap_swagger_data$fn__7626.invoke(middleware.clj:33)
	at compojure.api.middleware$wrap_options$fn__8906.invoke(middleware.clj:73)
	at muuntaja.middleware$wrap_format_request$fn__5234.invoke(middleware.clj:58)
	at compojure.api.middleware$wrap_exceptions$fn__8896.invoke(middleware.clj:42)
	at muuntaja.middleware$wrap_format_response$fn__5241.invoke(middleware.clj:80)
	at muuntaja.middleware$wrap_format_negotiate$fn__5237.invoke(middleware.clj:69)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__2562.invoke(keyword_params.clj:35)
	at ring.middleware.nested_params$wrap_nested_params$fn__2614.invoke(nested_params.clj:86)
	at ring.middleware.params$wrap_params$fn__2704.invoke(params.clj:64)
	at compojure.api.middleware$wrap_options$fn__8906.invoke(middleware.clj:73)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at ring.adapter.jetty$proxy_handler$fn__12737.invoke(jetty.clj:24)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by aoh** [comment]
Thanks. Should have been fixed yesterday. Reopen if still relevant.
